"""Create analyses table

Revision ID: 19c8b70188cb
Revises: 
Create Date: 2025-08-26 12:29:15.138223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c8b70188cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('emotion_joy', sa.Float(), nullable=True),
    sa.Column('emotion_sadness', sa.Float(), nullable=True),
    sa.Column('emotion_fear', sa.Float(), nullable=True),
    sa.Column('emotion_disgust', sa.Float(), nullable=True),
    sa.Column('emotion_anger', sa.Float(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
