"""Add session_id to Analysis model

Revision ID: 7fd6c77f602b
Revises: 19c8b70188cb
Create Date: 2025-08-27 10:05:23.317952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd6c77f602b'
down_revision = '19c8b70188cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_index(batch_op.f('ix_analyses_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
